# Generated by Django 3.2.9 on 2021-11-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
